library_root: "/Volumes/DharaWWL/SonosLibrary"
custom_dir: "/Volumes/DharaWWL/SonosLibrary/Sonos Customizations"

# easy directories
am_chant_src_dir: "/Volumes/DharaWWL/SonosLibrary/10 Day Morning Chantings"
am_chant_cust_dir: "/Volumes/DharaWWL/SonosLibrary/Sonos Customizations/10 Day Morning Chantings"
dohas_dir: "/Volumes/DharaWWL/SonosLibrary/10 Day Dohas"
gongs_dir: "/Volumes/DharaWWL/SonosLibrary/Sonos Customizations/VMC Alarms"
group_sittings_dir: "/Volumes/DharaWWL/SonosLibrary/Groupsittings/GSs English-only"
one_day_dir: "/Volumes/DharaWWL/SonosLibrary/1 Day Course Sets"
special_chantings_dir: "/Volumes/DharaWWL/SonosLibrary/Special Chantings"
workers_metta_dir: "/Volumes/DharaWWL/SonosLibrary/Workers Metta/Workers Metta 2005"

# hindi pdi special needs
hindi_instr_src_dir: "/Volumes/DharaWWL/SonosLibrary/10 Day Course Sets/10D Hindi-only/10D Hindi-only Instructions"
hindi_instr_cust_dir: "/Volumes/DharaWWL/SonosLibrary/Sonos Customizations/10D_Hindi_PDI"
# special album names
dohas_album: ''
group_sittings_album: ''
one_day_album: ''
special_chantings_album: ''
workers_metta_album: ''
hindi_PDI_album: '_Hindi PDIs'
